"""
config.py
=========
Tat ca hang so cau hinh cho Camera LiDAR Web V7.
"""
import sys

# ======================== CAU HINH ========================

YOLO_MODEL = 'yolov12n-face.pt'
YOLO_CONF = 0.45
YOLO_IMGSZ = 320
YOLO_CLASSES = None

CAMERA_INDEX = 0
FRAME_WIDTH = 640
FRAME_HEIGHT = 480

CAMERA_FOCAL_PX = 500.0
REAL_FACE_HEIGHT_M = 0.22
TARGET_DISTANCE_M = 0.8
DIST_DEADBAND_M = 0.10

TARGET_BBOX_H = 120
MIN_BBOX_H = 30
DIST_DEADBAND = 0.12
CENTER_DEADBAND = 0.05
CENTER_SETTLE_BAND = 0.10
FORWARD_ALIGN_LIMIT = 0.28
FORWARD_ALIGN_MIN_GAIN = 0.18

VX_MAX = 0.35
VY_MAX = 0.25
OMEGA_MAX = 1.5

VY_ALIGN_MAX = 0.22
OMEGA_ALIGN_MAX = 0.28
OMEGA_ALIGN_MIN = 0.05
VY_KP = 0.95
VY_KI = 0.04
VY_KD = 0.10
VY_ALIGN_DAMP_GAIN = 0.18
SMALL_ERR_X_FOR_VY = 0.12
LARGE_ERR_X_FOR_WZ = 0.30

CLOSE_BACKOFF_GAIN = 1.30
CLOSE_BACKOFF_MAX = 0.22

VX_SLEW_MPS_S = 0.90
VY_SLEW_MPS_S = 1.00
OMEGA_SLEW_RAD_S2 = 4.00

OMEGA_KP = 2.0
OMEGA_KI = 0.1
OMEGA_KD = 0.3
OMEGA_NEAR_CENTER_DAMP_GAIN = 0.22

ALIGN_HOLD_ENTER = 0.025
ALIGN_HOLD_EXIT = 0.045
ALIGN_STRAFE_ENTER = 0.075
ALIGN_STRAFE_EXIT = 0.135
ALIGN_RATE_HOLD = 0.035

TURN_KP = 1.85
TURN_KD = 0.42

STRAFE_KP = 0.95
STRAFE_KD = 0.24

HOLD_KP = 0.55
HOLD_KD = 0.18
HOLD_OMEGA_MAX = 0.10

TRACK_USE_IMU_HEADING = True
TRACK_IMU_STALE_S = 0.35
TRACK_HEADING_KP = 2.20
TRACK_HEADING_KI = 0.00
TRACK_HEADING_KD = 0.45
TRACK_HEADING_MAX = 0.28
TRACK_HEADING_TARGET_RATE_RAD_S = 1.60

ADAPT_GAIN_MIN = 0.70
ADAPT_GAIN_MAX = 1.15
ADAPT_OVERSHOOT_ERR = 0.040
ADAPT_OVERSHOOT_RATE = 0.030
ADAPT_DROP = 0.12
ADAPT_RECOVER_PER_S = 0.05

VX_KP = 0.8
VX_KI = 0.05
VX_KD = 0.15

OMEGA_FF_GAIN = 0.6
VX_FF_GAIN = 0.5

LOST_COAST_TIME = 0.3
LOST_SOFT_STOP = 0.8
LOST_HARD_RESET = 1.5

LOST_TIMEOUT = 0.8
CONTROL_RATE = 40

KALMAN_Q = 3.0
KALMAN_R = 1.0
KALMAN_VEL_DECAY = 0.95

HIST_LEN = 150
ARDUINO_PORT = '/dev/ttyUSB1' if sys.platform.startswith('linux') else None
LIDAR_PORT = '/dev/ttyUSB0' if sys.platform.startswith('linux') else 'COM14'
LIDAR_BAUDRATE = 460800
LIDAR_BAUDRATES = (460800, 256000, 115200)
LIDAR_PATH_LEN = 500

# ===== Point Cloud filtering config =====
PC_VOXEL_SIZE_M = 0.05
PC_SOR_K = 8
PC_SOR_STD_RATIO = 1.5
PC_MAX_POINTS = 4000
PC_DECAY_PER_SEC = 0.65
PC_MIN_ALPHA = 0.15
PC_RANGE_MIN_M = 0.15
PC_RANGE_MAX_M = 8.0
PC_SEND_EVERY_N_SCANS = 1

# ===== Persistent map (SLAM) config =====
MAP_FILE = 'lidar_map.npz'
MAP_VOXEL_SIZE_M = 0.08
MAP_MAX_POINTS = 30000
MAP_AUTOSAVE_PERIOD_S = 30.0
MAP_MIN_OBS_TO_KEEP = 3.5
MAP_SEND_EVERY_N_SCANS = 5
MAP_SEND_MAX_POINTS = 5000
RELOC_MAX_TRIES = 5
RELOC_MAX_MATCH_DIST_M = 2.0

# ===== Saved map locations / waypoint navigation =====
WAYPOINTS_FILE = 'map_waypoints.json'
WAYPOINT_LABEL_MAX_LEN = 48

# --- Tolerance ---
NAV_GOAL_TOLERANCE_M = 0.15
NAV_HEADING_TOLERANCE_DEG = 8.0
NAV_LIDAR_STALE_S = 1.0

# --- Phase machine thresholds ---
NAV_PATH_HEADING_TOL_DEG = 12.0
NAV_PATH_HEADING_HYST_DEG = 25.0

# --- Velocity limits ---
NAV_VX_MAX = 0.25
NAV_OMEGA_MAX = 1.20
NAV_VX_MIN_MOVE = 0.05
NAV_OMEGA_MIN_MOVE = 0.25

# --- P gains ---
NAV_HEADING_KP = 1.30
NAV_TRANSLATION_KP = 0.65

# --- Deceleration / slow-down zone ---
NAV_DECEL_DIST_M = 0.45
NAV_FINAL_APPROACH_M = 0.20

# --- Rate limits ---
NAV_VX_RATE_LIMIT = 0.6
NAV_OMEGA_RATE_LIMIT = 3.0

# ===== V7: A* Path Planning =====
ASTAR_RESOLUTION_M   = 0.15
ASTAR_INFLATE_M      = 0.22
ASTAR_SUBWP_TOL_M    = 0.30
ASTAR_REPLAN_DIST_M  = 1.00
ASTAR_REPLAN_PERIOD_S = 10.0

# ===== V7: Local Obstacle Avoidance =====
OBS_SAFE_DIST_M   = 0.40
OBS_SLOW_DIST_M   = 0.75
OBS_CONE_HALF_DEG = 22.0
OBS_MIN_POINTS    = 3

# ===== V7: Encoder Fusion =====
ENCODER_ICP_ALPHA   = 0.55
ENCODER_TRUST_SCANS = 3

# ===== Map: raycast occupancy =====
MAP_RAYCAST_FREE_DECREMENT = 0.35
MAP_RAYCAST_HIT_INCREMENT = 1.0
MAP_OBS_MAX = 20.0
MAP_MIN_OBS_TO_DISPLAY = 2.5
MAP_RAYCAST_MAX_RANGE_M = 6.0
MAP_RAYCAST_DOWNSAMPLE = 4
